- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_index.scss
- db/seeds.rb
Basic component style:
-Button
-card
-container
Beta seed style working on it.
> Style component and beta seed

- app/models/charity.rb
- app/models/offer.rb
- app/models/request.rb
- app/models/sweet.rb
- app/models/user.rb
- config/routes.rb
created relations (for every model no Review for now)
dont worry about the routes gonna work more on them
> created relations - gonna focus on routes even more

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
Hi Guys
I added colors into SCSS as well added header and body fonts.
As well as added a background color.
> changed fonts and added colors

- app/assets/stylesheets/components/_card.scss
- app/controllers/requests_controller.rb
- app/views/requests/index.html.erb
- config/routes.rb
Added the bare bone request with:
Routes
Controller index
Simple index.html.erb
> Bare bone request index

- app/controllers/requests_controller.rb
- app/views/requests/show.html.erb
- config/routes.rb
Added a delete button on the show page of the request. The controller destroy the dependent offer at the same time. After destroy the user is redirected to home page>
> Destroy on show request redirect to home page

- app/assets/stylesheets/pages/_home.scss
- app/views/shared/_navbar.html.erb
Hey guys!
Nav-bar is now linked to the correct routes
added a hover color
> Added links to navbar

- Gemfile
- Gemfile.lock
- app/controllers/requests_controller.rb
- app/models/request.rb
- app/views/requests/index.html.erb
- config/routes.rb
Added search bar to the request index. you can search by country and name of sweet!
> Added a lovely search bar for request by country and candy name

- app/controllers/pages_controller.rb
- app/models/offer.rb
- app/views/pages/profile.html.erb
- app/views/pages/shared/_user_info.html.erb
- db/migrate/20190828134746_add_default_to_status.rb
- db/migrate/20190828135511_add_default_to_status_a_again.rb
- db/migrate/20190828135828_add_default_status_to_offer.rb
- db/migrate/20190828140018_add_default_status_to_offer_again.rb
- db/schema.rb
- db/seeds.rb
added user information
changed the seeds because added enum status
> added user information, changed the seeds because added enum status

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/views/offers/show.html.erb
- app/views/requests/index.html.erb
Hey, parrots!
I worked on the show page for the details on an offer.
> detail on the offer

- Gemfile
- Gemfile.lock
- app/controllers/requests_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/sweet.rb
- app/views/layouts/application.html.erb
- app/views/requests/_info_window.html.erb
- app/views/requests/_request_index.html.erb
- app/views/requests/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20190828154252_add_coordinates_to_sweet.rb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
Added the maps to the request index.
The maps still need to be put in a container and boutify a tiny bit.
> Maps on request index with pop. Need to be styled

- app/assets/stylesheets/components/_button.scss
- app/views/offers/new.html.erb
- app/views/pages/home.html.erb
- app/views/requests/new.html.erb
- app/views/requests/show.html.erb
- app/views/sweets/index.html.erb
Hey Guys!
I linked all views to the correct routes. let me know what ya think.
> Linked up pages

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/views/layouts/application.html.erb
- app/views/sweets/index.html.erb
Hey guys!
Added CSS style on the sweet cards which are on the sweet index page.
get them out
> CSS style on the sweet cards on the browse page

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_search-bar.scss
- app/views/layouts/application.html.erb
- app/views/requests/_request_index.html.erb
- app/views/requests/index.html.erb
> Half baked style for the index request

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/pages_controller.rb
- app/models/offer.rb
- app/views/pages/profile.html.erb
- app/views/pages/shared/_offer_tab.html.erb
- app/views/pages/shared/_request_tab.html.erb
- app/views/pages/shared/_user_info.html.erb
- db/seeds.rb
Hey guys,
I styled the profile today :-) 
I also had to change the seeds (because of the offer status, so dont forget to db:seed next time)
Here are some screenshots of today's work
Gonna work on it tomorrow again:
> Profile details

- app/assets/stylesheets/components/_container.scss
- app/controllers/requests_controller.rb
- app/helpers/money_converter_helper.rb
- app/views/layouts/application.html.erb
- app/views/requests/index.html.erb
- app/views/requests/new.html.erb
- app/views/sweets/index.html.erb
Style the map:
The map is side by side with the request card
The map is sticky
Request Controller:
-Refactor the geocode into a private method
Site Name:
Added Sweet Travel on browser tab title
Sweet Index:
Added class to title so text is centre.
Money conversion for Request New - the problem:
The request new was saving directly the donation and price in cents. The user expect the price to be in euro. 
What I did:
Added a new helper to convert the euro into cents
Implemented the helper into the request controller.
Please don't look at the request controller line 31, 32, 33. Those are dirty, dirty, dirty. I had to do that otherwise when failing to save the render:new who display the cent amount. Those line will need refactor after Friday.
e.g. the user insert 42 for donation and forget to …
> Style map and more

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/requests/_request_details.html.erb
- app/views/requests/show.html.erb
Boutify the show request. Now the card don't fly to the right side. Style need some love.
Also change the font to red hat (same as the one we use on figma) for the body website wide.
> Some styling on the show request page

- app/assets/stylesheets/components/_card.scss
- app/views/offers/new.html.erb
- app/views/offers/show.html.erb
Hey guys
I added the container-top class to all the remaining H1
> added container-top to all H1

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
I made some small bufixes
- on homepage
- dashboard
> small fixes

- app/views/pages/home.html.erb
Hey sweetie,
I changed the wording on the landing page.
> changed the wording on the landing page

- app/assets/stylesheets/components/_button.scss
- app/views/offers/shared/_form-offer.html.erb
- app/views/offers/show.html.erb
> Button on offer new and offer show

- app/views/pages/home.html.erb
- app/views/requests/index.html.erb
- app/views/requests/new.html.erb
> changed some text

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_icon.scss
- app/assets/stylesheets/components/_index.scss
- app/views/requests/_request_details.html.erb
- app/views/requests/show.html.erb
> New style for show request

- app/controllers/sweets_controller.rb
- app/models/sweet.rb
- app/views/sweets/index.html.erb
- config/routes.rb
Search bar for candy. User can search by name, category and country of the candy.
BEFORE:
AFTER:
> Search bar for candy index

- app/assets/stylesheets/components/_container.scss
- app/views/requests/index.html.erb
- app/views/sweets/index.html.erb
Hey guys,
I changed the font and wording on the sweet index as well as on the candy request page
> Changed the headers for request and sweet page

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/home.html.erb
Hey 
I added a footer to the homepage
> footer was added

- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_search-bar.scss
- app/assets/stylesheets/components/_text.scss
- app/views/requests/index.html.erb
added second searchbar (frontend)
> added second searchbar only frontend

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_margin.scss
- app/views/requests/new.html.erb
Hey guys,
I redesigned the new request form 
check it out
> redesigned the new request form

- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/requests_controller.rb
- app/models/offer.rb
- app/models/request.rb
- app/views/offers/show.html.erb
- app/views/pages/shared/_offer_tab.html.erb
- app/views/pages/shared/_user_info.html.erb
- app/views/requests/_request_details.html.erb
- app/views/requests/_request_index.html.erb
- app/views/requests/index.html.erb
- db/migrate/20190903100658_add_city_to_user.rb
- db/schema.rb
- db/seeds.rb
Added a city to the user and added  to the view:
-Request index
-Request show
-Profile
-Offer show
Style:
-the user div on profile
-the Offer show to have offer info and chat side by side
-Added blue shadow on map.
Screen shot:
> Implemented the city for user

- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_container.scss
- app/views/requests/new.html.erb
Hey guys,
I updated the html on the request new page.
> spacing on request

- app/controllers/requests_controller.rb
- app/models/request.rb
- app/views/requests/index.html.erb
- db/seeds.rb
The search bar is actually working now!
> Fix the search bar

- app/assets/stylesheets/components/_container.scss
- app/views/requests/new.html.erb
Hey losers,
AGAIN! Updated the new request page. Added more charities.
> added more charity

- app/assets/stylesheets/components/_card.scss
Hey guys,
Added some space on the offers in the profile page
> added space on the offer

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/controllers/statusoffer_controller.rb
- app/models/offer.rb
- app/views/layouts/application.html.erb
- app/views/pages/shared/_offer_tab.html.erb
- app/views/pages/shared/_request_tab.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/statusoffer_controller_test.rb
Added the Accept or decline offer feature. Added the button on the request card in the profile
BEFORE:
AFTER:
> Accept and Decline offer feature

- app/assets/stylesheets/components/_container.scss
- app/views/requests/_request_index.html.erb
- app/views/requests/index.html.erb
- app/views/sweets/index.html.erb
Hey guys,
I added some giphys to the request page as well as on the sweet page
> Added cool giphy on the request page

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> Hp version 2

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Fixed the navbar
+ got rid of avatar
+ designed on beamer - check
> fixed navbar and homepage

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> navbar quick fix

- Gemfile
- Gemfile.lock
- app/controllers/orders_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/payments_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/confirm_alert.js
- app/models/order.rb
- app/models/request.rb
- app/models/user.rb
- app/views/orders/show.html.erb
- app/views/pages/shared/_request_tab.html.erb
- app/views/payments/new.html.erb
- config/initializers/money.rb
- config/initializers/stripe.rb
- config/routes.rb
- db/migrate/20190904090945_create_orders.rb
- db/migrate/20190904092241_remove_request_from_orders.rb
- db/migrate/20190904092408_add_user_to_order.rb
- db/migrate/20190904112201_add_offer_to_order.rb
- db/schema.rb
- db/seeds.rb
- package.json
- test/controllers/orders_controller_test.rb
- test/controllers/payments_controller_test.rb
- test/models/order_test.rb
- yarn.lock
Change the button show to the user depending on the status of the offers. If an offer has been validated it only show the validate offer. If not it show all the offer with two buttons to decline or approved the offer. If offer is validate you got a button to proceed to payment.
> button request in the profile + Stripe

- app/assets/stylesheets/components/_container.scss
- app/views/pages/home.html.erb
- app/views/pages/profile.html.erb
changed default tab 
+ padding on the "how it works section"
> change default tab

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_payment.scss
- app/assets/stylesheets/config/_colors.scss
- app/models/request.rb
- app/views/payments/new.html.erb
> Re-designed checkout page

- app/views/orders/show.html.erb
- app/views/payments/new.html.erb
> Order confirm design

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_container.scss
- app/views/sweets/index.html.erb
Hey guys,
So I changed the border-radius and changed the sweet index page.
check it out
> changed borders as well as changed cards in sweet index

- app/assets/stylesheets/components/_card.scss
- app/views/requests/_request_index.html.erb
- app/views/sweets/index.html.erb
Hey guys,
I redesigned the request card 
from this 
to this
> redesigned the request card

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/offers/show.html.erb
> changes to chat paige

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/offers_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/statusoffer_controller.rb
- app/models/request.rb
- app/views/pages/profile.html.erb
- app/views/pages/shared/_request_tab.html.erb
> a more boutiful profile with request

- app/controllers/requests_controller.rb
- app/views/requests/index.html.erb
Hey guys,
I changed the size of the map so that it fits in the page now.
> new round map

- app/javascript/plugins/confirm_alert.js
- app/views/pages/profile.html.erb
> New message on the pop confirm

- app/views/pages/home.html.erb
- app/views/pages/profile.html.erb
> profile fix

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/requests/_request_details.html.erb
- app/views/requests/_request_index.html.erb
Hey guys,
I added some space between the text in the request page
> Font color

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
worked on the homepage to make it look nice on screen
> nicer homepage
